"""Replace price_history surrogate id PK with composite natural key.

Drops the `id` column and its pkey index (~80 MB at 2.8M rows) and promotes
(item_id, timestamp, source) — previously a unique constraint — to the primary
key. The PK is built fresh, which also discards bloat accumulated in the old
unique index. All writers upsert via ON CONFLICT (item_id, timestamp, source),
which the PK arbitrates, so no insert paths change.

Run `VACUUM FULL price_history` after this migration to rewrite the heap and
reclaim the dropped column plus dead space (VACUUM cannot run inside the
migration transaction).

Revision ID: 0006_price_history_composite_pk
Revises: 0005_add_performance_indexes
Create Date: 2026-07-07
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0006_price_history_composite_pk"
down_revision = "0005_add_performance_indexes"
branch_labels = None
depends_on = None

PK_COLUMNS = ["item_id", "timestamp", "source"]


def upgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        # Redundant prefix of the new PK; exists only in some environments.
        op.execute("DROP INDEX IF EXISTS idx_price_history_item_timestamp")
        op.execute("ALTER TABLE price_history DROP CONSTRAINT price_history_pkey")
        op.execute("ALTER TABLE price_history DROP COLUMN id")
        op.execute("ALTER TABLE price_history DROP CONSTRAINT uq_price_history_item_timestamp_source")
        op.execute("ALTER TABLE price_history ALTER COLUMN source SET NOT NULL")
        op.execute(
            "ALTER TABLE price_history ADD CONSTRAINT price_history_pkey PRIMARY KEY (item_id, timestamp, source)"
        )
    else:
        # SQLite: batch mode recreates the table with the new schema.
        inspector = sa.inspect(bind)
        index_names = {idx["name"] for idx in inspector.get_indexes("price_history")}
        with op.batch_alter_table("price_history", recreate="always") as batch:
            if "idx_price_history_item_timestamp" in index_names:
                batch.drop_index("idx_price_history_item_timestamp")
            batch.drop_constraint("uq_price_history_item_timestamp_source", type_="unique")
            batch.drop_column("id")
            batch.create_primary_key("price_history_pkey", PK_COLUMNS)


def downgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE price_history DROP CONSTRAINT price_history_pkey")
        op.execute("ALTER TABLE price_history ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY")
        op.execute("ALTER TABLE price_history ADD PRIMARY KEY (id)")
        op.execute(
            "ALTER TABLE price_history "
            "ADD CONSTRAINT uq_price_history_item_timestamp_source "
            "UNIQUE (item_id, timestamp, source)"
        )
    else:
        with op.batch_alter_table("price_history", recreate="always") as batch:
            batch.drop_constraint("price_history_pkey", type_="primary")
            batch.add_column(sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True))
            batch.create_unique_constraint("uq_price_history_item_timestamp_source", PK_COLUMNS)
